---
wp_db_collate: ""
wp_table_prefix: "datascientest_"
wp_debug: false
wp_admin_email: "admin@example.invalid"

wp_version: latest
wp_install_dir: "/var/www/html"

wp_webserver: nginx
wp_sitename: wordpress.local

wp_db_name: "datascientest"
wp_db_user: "datascientest"
wp_db_host: "localhost"
wp_db_charset: "utf8"
