---
# WordPress
wp_archive_url: https://wordpress.org/latest.tar.gz
wp_install_parent: /var/www/html
wp_install_dir: /var/www/html/wordpress
wp_sitename: _
wp_debug: false
wp_table_prefix: datascientest_

# Web server
wp_webserver: nginx

# Database
wp_db_name: wordpress
wp_db_user: wordpress
wp_db_password: lab-only-demo-password
wp_db_host: localhost
wp_db_charset: utf8mb4
wp_db_collate: ""
