---
galaxy_info:
  author: DataScientest Sprint 17 lab
  description: Rôle pédagogique WordPress + Nginx + MySQL pour Ubuntu 24.04
  license: MIT
  min_ansible_version: '2.15'
  platforms:
    - name: Ubuntu
      versions:
        - noble

dependencies: []
