---
django_app_name: datascientest_django
django_system_user: django
django_system_group: django
django_install_dir: /opt/datascientest-django
django_venv_dir: /opt/datascientest-django/.venv
django_settings_module: config.settings
django_allowed_hosts: "localhost,127.0.0.1,{{ groups['app'][0] }},{{ hostvars[groups['app'][0]].ansible_host }}"
django_debug: false
django_gunicorn_bind: 127.0.0.1:8000

postgresql_database: django_app
postgresql_user: django_app
postgresql_port: 5432
postgresql_host: 127.0.0.1
postgresql_listen_addresses: "127.0.0.1"
postgresql_app_cidr: 127.0.0.1/32

redis_host: 127.0.0.1
redis_bind_address: 127.0.0.1
redis_port: 6379
redis_broker_database: 0
redis_result_database: 1

celery_service_name: datascientest-celery
celery_concurrency: 2
celery_beat_service_name: datascientest-celery-beat
celery_beat_demo_interval_seconds: 30
