---
galaxy_info:
  role_name: compose_stack
  author: Thomas AWOUNFOUET
  description: Deploy the multi-environment Django Docker Compose stack.
  license: MIT
  min_ansible_version: "2.16"
  platforms:
    - name: Ubuntu
      versions:
        - noble

dependencies: []
